service: users

provider:
  name: aws
  runtime: nodejs12.x

functions:
  users:
    handler: handler.users
    layers:
      - arn:aws:lambda:us-east-1:885121665536:layer:logging:8
    events: 
      - http:
          path: users
          method: get
