service: todos

provider:
  name: aws
  runtime: nodejs12.x

functions:
  todos:
    handler: handler.todos
    layers:
      - arn:aws:lambda:us-east-1:885121665536:layer:logging:8
    events: 
      - http:
          path: todos
          method: get
